// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CreateCartIfNotExists(ctx context.Context, arg CreateCartIfNotExistsParams) (Cart, error)
	DeleteCart(ctx context.Context, id uuid.UUID) (int64, error)
	DeleteCartItem(ctx context.Context, arg DeleteCartItemParams) (int64, error)
	DeleteExpiredCarts(ctx context.Context) (int64, error)
	GetCart(ctx context.Context, id uuid.UUID) (Cart, error)
	ListItems(ctx context.Context, cartID uuid.UUID) ([]CartItem, error)
	UpdateCartStatus(ctx context.Context, arg UpdateCartStatusParams) error
	UpdateQuantity(ctx context.Context, arg UpdateQuantityParams) (int64, error)
	UpsertCartItem(ctx context.Context, arg UpsertCartItemParams) error
}

var _ Querier = (*Queries)(nil)
