// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: client.sql

package db

import (
	"context"
)

const getById = `-- name: GetById :one
SELECT c.id,
       c.secret_hash,
       c.roles,
       c.status,
       c.created_at
FROM clients c WHERE id = $1
`

func (q *Queries) GetById(ctx context.Context, id string) (Client, error) {
	row := q.db.QueryRow(ctx, getById, id)
	var i Client
	err := row.Scan(
		&i.ID,
		&i.SecretHash,
		&i.Roles,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}
