// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Client struct {
	ID         string             `json:"id"`
	SecretHash string             `json:"secret_hash"`
	Roles      []string           `json:"roles"`
	Status     int16              `json:"status"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type Role struct {
	ID   int16  `json:"id"`
	Name string `json:"name"`
}

type User struct {
	ID           pgtype.UUID        `json:"id"`
	Email        string             `json:"email"`
	PasswordHash string             `json:"password_hash"`
	Status       int16              `json:"status"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type UserRole struct {
	UserID pgtype.UUID `json:"user_id"`
	RoleID int16       `json:"role_id"`
}
