// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"context"
)

type Querier interface {
	CreateUser(ctx context.Context, arg CreateUserParams) (AuthUser, error)
	GetUserByEmail(ctx context.Context, email string) (AuthUser, error)
	ListUsers(ctx context.Context, arg ListUsersParams) ([]AuthUser, error)
}

var _ Querier = (*Queries)(nil)
